services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: mc
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "2048M"
      MAX_PLAYERS: "100"
      MOTD: "Lobby For OneMCSever Proxy."
      ONLINE_MODE: "false"
      DIFFICULTY: "0"
      PVP: "false"
      MODE: "3"
      FORCE_GAMEMODE: "true"
      ALLOW_NETHER: "false"
      SPAWN_ANIMALS: "false"
      SPAWN_MONSTERS: "false"
      SPAWN_NPCS: "false"
      ENTITY_BROADCAST_RANGE_PERCENTAGE: "10"
      SIMULATION_DISTANCE: "3"
      VIEW_DISTANCE: "3"
      SEED: "1"
      LEVEL_TYPE: "flat"
      GENERATOR_SETTINGS: |-
        {"layers":[{"block":"minecraft:air","height":1}],"biome":"minecraft:plains"}
      GENERATE_STRUCTURES: "false"
      SPAWN_PROTECTION: "0"
      MAX_WORLD_SIZE: "1000"
      RATE_LIMIT: "0"
      ENFORCE_SECURE_PROFILE: "false"
      ACCEPTS_TRANSFERS: "true"
      PATCH_DEFINITIONS: /patch.json
      CFG_VELOCITY_SECRET_FILE: /velocity-secret
      ENV_VARIABLE_PREFIX: "CFG_"
      REPLACE_ENV_VARIABLES: "TRUE"
    volumes:
      - "./mcdata:/data"
      - "./patch.json:/patch.json:ro"
      - "./velocitydata/forwarding.secret:/velocity-secret:ro"
    restart: unless-stopped
    networks:
      - default

  mongo:
    volumes:
      - ./mongodata:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping').ok", "--quiet" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - default

  velocity:
    image: itzg/mc-proxy:java25
    container_name: onemcserver
    tty: true
    stdin_open: true
    ports:
      - "25565:25577"
      - "19132:19132"
    environment:
      PROXY_NAME: "OneMcServerVelocity"
      ONLINE_MODE: "FALSE"
      TYPE: "VELOCITY"
      MEMORY: "512m"
      PLUGINS: |-
        https://github.com/koboshchan/OneMcServerVelocity/releases/latest/download/OneMcServerVelocity.jar
        https://cdn.modrinth.com/data/TsLS8Py5/versions/2PjHGlwd/SkinsRestorer.jar?mr_download_reason=standalone
        https://ci.lucko.me/job/spark/524/artifact/spark-velocity/build/libs/spark-1.10.172-velocity.jar
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/velocity
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/velocity
        https://cdn.modrinth.com/data/P1OZGk5p/versions/ruzmiBqe/ViaVersion-5.10.0.jar?mr_download_reason=standalone&mr_game_version=26.2&mr_loader=velocity
        https://cdn.modrinth.com/data/NpvuJQoq/versions/YjpKsm6j/ViaBackwards-5.10.0.jar?mr_download_reason=standalone&mr_game_version=26.2&mr_loader=velocity
      # JVM_OPTS: "-Dvelocity.packet-decode-logging=true"
    volumes:
      - ./velocitydata:/server
      # - ./build/libs/OneMcServerVelocity-1.0.jar:/server/plugins/onemcservervelocity.jar
    restart: unless-stopped
    depends_on:
      - mc
      - mongo
    networks:
      - default
      - onemcserver_bridge

networks:
  onemcserver_bridge:
      name: onemcserver_bridge


# to add servers to the network, add the following to the server's container service definition:
# networks:
#   - onemcserver_bridge

# and connect the compose project to the bridge network with the following configuration:
# networks:
#   onemcserver_bridge:
#     external: true